apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: my-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: nodejs-app
        image: nashaat111/frontend-app:latest
        ports:
        - containerPort: 3000

